<a href="https://colab.research.google.com/github/Kuhi484/Machine_Learning_/blob/Basics/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np

Numpy vs List

In [58]:
from time import process_time

In [59]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in range(10000)]

end_time = process_time()

print(end_time - start_time)

0.0009827000000015573


In [60]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0003328010000060999


Numpy Array

In [61]:
list1 = [1,2,3,4,5,6]

print(list1)

type(list1)

[1, 2, 3, 4, 5, 6]


list

In [62]:
np_array = np.array([1,2,3,4,5,6,7])
print(np_array)
type(np_array)

[1 2 3 4 5 6 7]


numpy.ndarray

In [63]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [64]:

a.shape #show the number of columns and rows

(5,)

In [65]:
#create 2D array
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [66]:
b.shape

(2, 5)

In [67]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [68]:
#Create a numpy array as Zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [69]:
#Create a numpy array as ones

y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
#Create a numpy array as values

z = np.full((4,5),6)
print(z)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [71]:
#Create a numpy array as Zeros

identical = np.eye(5)
print(identical)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [72]:
#create random array element
random = np.random.random((4,5))
print(random)

[[0.09695894 0.73942591 0.83464768 0.23578727 0.93475283]
 [0.85844932 0.87516856 0.99243723 0.77693368 0.18781096]
 [0.77451056 0.11317537 0.75140066 0.74360789 0.70185051]
 [0.61965524 0.78436292 0.2768273  0.40868556 0.48970255]]


In [73]:
#create random int array element
random = np.random.randint(10,1000,(4,5))
print(random)

[[844 549 408 107 471]
 [814 208 651 638 426]
 [518 618 627 531 381]
 [127 990 775 964 677]]


In [74]:
#create random array element in a range with size
space = np.linspace(10,30,6)
print(space)

[10. 14. 18. 22. 26. 30.]


In [75]:
#create random array element in a range with equal space
evenspace = np.arange(10,500,9)
print(evenspace)

[ 10  19  28  37  46  55  64  73  82  91 100 109 118 127 136 145 154 163
 172 181 190 199 208 217 226 235 244 253 262 271 280 289 298 307 316 325
 334 343 352 361 370 379 388 397 406 415 424 433 442 451 460 469 478 487
 496]


In [76]:
#convert a list into a numpy
list2 = [1,2,3,4,5,6,7,8,9]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [77]:
array = np.random.randint(10,50,(6,5))
print(array)

[[39 42 38 30 20]
 [39 23 30 19 46]
 [27 23 29 32 39]
 [22 14 26 36 18]
 [46 14 32 18 46]
 [22 16 29 13 31]]


In [78]:
print(array.ndim) #shows the dimension

2


In [79]:
print(array.size) #shows array size

30


In [80]:
print(array.shape) #shows number of rows and column

(6, 5)


In [81]:
print(array.dtype) #shows the type of the elements

int64


In [82]:
a = np.random.randint(0,10,(4,5))
b = np.random.randint(0,10,(4,5))

In [83]:
print(a)
print(b)

[[7 2 7 6 3]
 [9 8 8 0 7]
 [0 3 4 3 6]
 [1 6 3 0 0]]
[[0 6 1 4 9]
 [4 2 0 8 0]
 [0 6 2 3 5]
 [1 7 1 1 9]]


In [84]:
#maths operation on the array in numpy
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 7  8  8 10 12]
 [13 10  8  8  7]
 [ 0  9  6  6 11]
 [ 2 13  4  1  9]]
[[ 7 -4  6  2 -6]
 [ 5  6  8 -8  7]
 [ 0 -3  2  0  1]
 [ 0 -1  2 -1 -9]]
[[ 0 12  7 24 27]
 [36 16  0  0  0]
 [ 0 18  8  9 30]
 [ 1 42  3  0  0]]
[[       inf 0.33333333 7.         1.5        0.33333333]
 [2.25       4.                inf 0.                inf]
 [       nan 0.5        2.         1.         1.2       ]
 [1.         0.85714286 3.         0.         0.        ]]


<ipython-input-84-4cf84e0fcb1d>:5: RuntimeWarning: divide by zero encountered in divide
  print(a/b)
<ipython-input-84-4cf84e0fcb1d>:5: RuntimeWarning: invalid value encountered in divide
  print(a/b)


In [87]:
array = np.random.randint(0,10,(3,4))
print(array)
print(array.shape)

[[6 3 0 3]
 [2 0 4 3]
 [1 6 5 9]]
(3, 4)


In [88]:
#transpose of array

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[6 2 1]
 [3 0 6]
 [0 4 5]
 [3 3 9]]
(4, 3)


In [89]:
trans2 = array.T
print(trans2)

[[6 2 1]
 [3 0 6]
 [0 4 5]
 [3 3 9]]


In [92]:
array = np.random.randint(10,20,(5,4))
print(array)
print(array.shape)

[[13 14 12 12]
 [16 19 13 10]
 [19 15 10 14]
 [15 14 19 18]
 [18 11 11 16]]
(5, 4)


In [93]:
array2 = np.reshape(array,(4,5))
print(array2)
print(array2.shape)

[[13 14 12 12 16]
 [19 13 10 19 15]
 [10 14 15 14 19]
 [18 18 11 11 16]]
(4, 5)
